# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-23 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_api_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='apigroup',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
            preserve_default=False,
        ),
    ]
