# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-24 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_apigroup_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apigroup',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apigroup',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ApiGroup'),
        ),
    ]
