# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-24 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180524_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apigroup',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.ApiGroup'),
        ),
    ]
