# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-27 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=20)),
                ('type', models.IntegerField()),
                ('kind', models.IntegerField()),
                ('required', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='api',
            name='status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiparam',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Api'),
        ),
    ]
