# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-27 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180527_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='api.Api'),
        ),
    ]
