# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180527_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apiparam',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='api.Api'),
        ),
    ]
