# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180528_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='apiparam',
            name='desc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='apiparam',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
