# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180528_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTestHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_info', models.TextField()),
                ('response_info', models.TextField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Api')),
            ],
        ),
    ]
