# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-01 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_apitesthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiBodyParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('exam', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.IntegerField()),
                ('required', models.BooleanField()),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_params', to='api.Api')),
            ],
        ),
        migrations.CreateModel(
            name='ApiResponseParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.IntegerField()),
                ('required', models.BooleanField()),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_params', to='api.Api')),
            ],
        ),
        migrations.CreateModel(
            name='ApiUrlParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('exam', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.CharField(blank=True, max_length=20, null=True)),
                ('required', models.BooleanField()),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_params', to='api.Api')),
            ],
        ),
        migrations.RenameModel(
            old_name='Header',
            new_name='ApiHeader',
        ),
        migrations.RemoveField(
            model_name='apiparam',
            name='api',
        ),
        migrations.DeleteModel(
            name='ApiParam',
        ),
    ]
