# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-01 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180601_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='status',
            field=models.IntegerField(),
        ),
    ]
