# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-05 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180602_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiEnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
                ('prefix_url', models.CharField(blank=True, max_length=20, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ApiEnvHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=50)),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ApiEnv')),
            ],
        ),
        migrations.CreateModel(
            name='ApiEnvParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=50)),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ApiEnv')),
            ],
        ),
    ]
