# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-05 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_apienv_apienvheader_apienvparam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apienvheader',
            name='env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_headers', to='api.ApiEnv'),
        ),
        migrations.AlterField(
            model_name='apienvparam',
            name='env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_params', to='api.ApiEnv'),
        ),
    ]
